### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Cir0X** [qmetric/spark-authentication#1]
Hey,

I tried to use the library for basic auth, but an IncompatibleClassChangeError gets thrown:

	Exception in thread "main" java.lang.IncompatibleClassChangeError: class com.qmetric.spark.authentication.BasicAuthenticationFilter has interface spark.Filter as super class
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
		at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Using spark 2.3

**Comment by qmg-mburns** [comment]
Try version 1.2

**Comment by Cir0X** [comment]
Thanks!
Works fine with 1.2

**Comment by kedare** [comment]
Any plan to publish it on Maven ? :)
I can only find 1.1 and 1.0.

**Comment by SoltauFintel** [comment]
+1 for publish to Maven

Workaround: Just copy the two v1.2 Java files to your project and it works.
(with server='com.sparkjava:spark-core:2.3', client='com.sun.jersey:jersey-client:1.19')

**Comment by huwtl** [comment]
this has been released
