### ISSUE TITLE
Spark-authentication seems to be not compatible with Spark 2.5.5

### ISSUE THREAD

**Issue by evgenius** [qmetric/spark-authentication#4]
Spark authors changed the signature of the halt() method in the version 2.5.5.
Now calling halt(401) throws a HaltException.
So instead of getting an authorization dialog in browser, I see the 500 error now.
```
java.lang.NoSuchMethodError: spark.Spark.halt(I)V
	at com.qmetric.spark.authentication.BasicAuthenticationFilter.handle(BasicAuthenticationFilter.java:41) ~[spark-authentication-1.3.jar:?]
	at com.mz.auth.cache.service.HttpService.lambda$run$0(HttpService.java:87) ~[main/:?]
	at spark.FilterImpl$1.handle(FilterImpl.java:62) ~[spark-core-2.5.5.jar:?]
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48) ~[spark-core-2.5.5.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:129) ~[spark-core-2.5.5.jar:?]
```

**Comment by evgenius** [comment]
https://github.com/perwendel/spark/compare/2.5.4...2.5.5

**Comment by huwtl** [comment]
Should be fixed now
